### ISSUE TITLE
Question: Is it possible to use this in a project as a github submodule. 

### ISSUE THREAD

**Issue by JimmyPedersen** [Zellaco/Process#8]
Evaluate if this is a good idea, would it increase the usability, any gains?

**Comment by johekb** [comment]
I'm not so familiar with the sub-module concept and basically I have 2 questions:
1. If you use sub-modules can you then control which version of the sub-module that should be used or do you always get the 'latest'?
2. The drawback as I see it is that the templates for both issues and review checklists is put in the .github folder and I think this need to be in the top-level in order for GitHub to recognise it.

**Comment by JimmyPedersen** [comment]
1. You get the version(the exact commit )you last pulled of the sub-module repo before committing the main project.
example: [git sub-module used in one of our projects](https://github.com/Zellaco/UBD-IR_Station/tree/main/IR_Station)
I don't even think it's possible to have automatically get the latest version of the sub-module.
If you haven't used sub-modules I highly recommend it

2. That I don't know anything about, haven't tried using Github CI/templates etc. But it makes sense that it would need to be in the top directory.

**Comment by johekb** [comment]
I played around with sub-modules a bit and found the following:
1) The sub-module gets its own directory i.e. Process --> if we go for sub-modules then #9 get strange.
2) the templates in - .github will not work --> We can make it as a part of the project creation step-by-step instruction to copy the .github module from the sub-module to the root directory.
3) An alternative would be to always start a new project by forking the Process repository. I tested it in https://github.com/Zellaco/SuperNewProject 
In that case we should add #9
When a new process is done it is possible for the project to do a sync from the upstream Process repository which should work smoothly

**Comment by johekb** [comment]
After think a second time to this I think the best way is not to use sub-modules in this particular use-case. Main reason is that it should be possible for the project to "tailor" the process to the customer. Such tailoring is project unique and should not be merged back to the main process.

Instead we should go with the proposal above i.e. forking the process repository when a new project is started.

This issue is closed.
